// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "rac9PLTsLeW3jlaWfDlFTf8UswYpXaOb7h4caE0taNai5bIZdmf2knmLEMcKMvfOd4IRwO";
}
}
}

